# @package _group_
_target_: pytorch_lightning.Trainer
accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: False
auto_scale_batch_size: False
auto_select_gpus: True
benchmark: False
check_val_every_n_epoch: 1
checkpoint_callback: True
deterministic: False
fast_dev_run: False
flush_logs_every_n_steps: 100
gpus: null
gradient_clip_val: 0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
max_epochs: 1000
max_steps: null
min_epochs: 1
min_steps: null
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: 32
prepare_data_per_node: True
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: False
replace_sampler_ddp: True
sync_batchnorm: False
terminate_on_nan: False
tpu_cores: null
track_grad_norm: -1
truncated_bptt_steps: null
val_check_interval: 1.0
weights_save_path: null
weights_summary: top
